Fixes to easy-rsa/2.0
As support for OpenSSL 1.0.0 requires a modified openssl.cnf file, it was
decided to rename openssl.cnf to openssl-1.0.0.cnf for clarity and better
support of different OpenSSL versions. The old openssl.cnf was renamed as
openssl-0.9.8.cnf.

This patch makes sure that all openssl*.cnf files are copied when running 'make
install' in easy-rsa and makes the whichopensslcnf script aware of them as well.

Signed-off-by: Samuli Seppänen <samuli@openvpn.net>
Acked-by: David Sommerseth <davids@redhat.com>
Signed-off-by: David Sommerseth <davids@redhat.com>

diff --git a/easy-rsa/2.0/whichopensslcnf b/easy-rsa/2.0/whichopensslcnf
--- a/easy-rsa/2.0/whichopensslcnf
+++ b/easy-rsa/2.0/whichopensslcnf
@@ -1,13 +1,26 @@
 #!/bin/sh
 
+cnf="$1/openssl.cnf"
+
 if [ "$OPENSSL" ]; then
-	if $OPENSSL version | grep 0.9.6 > /dev/null; then
-		echo "$1/openssl-0.9.6.cnf"
+	if $OPENSSL version | grep -E "0\.9\.6[[:alnum:]]" > /dev/null; then
+		cnf="$1/openssl-0.9.6.cnf"
+	elif $OPENSSL version | grep -E "0\.9\.8[[:alnum:]]" > /dev/null; then
+		cnf="$1/openssl-0.9.8.cnf"
+	elif $OPENSSL version | grep -E "1\.0\.([[:digit:]][[:alnum:]])" > /dev/null; then
+                cnf="$1/openssl-1.0.0.cnf"
 	else
-		echo "$1/openssl.cnf"
+		cnf="$1/openssl.cnf"
 	fi
-else
-	echo "$1/openssl.cnf"
+fi
+
+echo $cnf
+
+if [ ! -r $cnf ]; then
+    echo "**************************************************************" >&2
+    echo "  No $cnf file could be found" >&2
+    echo "  Further invocations will fail" >&2
+    echo "**************************************************************" >&2
 fi
 
 exit 0
